# Numpy 
NumPy is made for large datasets because Python loops are slow compared to it. It is an open-source Python library used for scientific computing, data analysis, and heavy mathematical operations.


In [ ]:
import numpy as np
# basics code of the numpy
temperatures = np.array([33.5, 34.2, 35.0, 36.8, 37.6, 38.4, 39.2, 40.0, 41.0, 42.0])
avarage = np.mean(temperatures)
print(round(avarage,2))

37.77


In [ ]:
import numpy as np
# there are many types of numpy arrays
# the most common is the ndarray
matrix = np.array([[1, 2, 3], [4, 5, 6]])
#  default array type is float
defaultArrays = np.ones((2, 2))
zeroesArrays = np.zeros((2, 2))
defaultNumberArrays = np.full((2,2),5)
arrangedArrays = np.arange(6).reshape(2,3)
identityMatrix = np.eye(3)

#  default array type is int


There are many ways for checking the arrays like what these are and what these do. **Shape** tells us about the number of rows and columns meanwhile **size** tells us the total number of elements in the array. **NDIM** tells us how many dimensions the array has. **Dtype** tells us what type of data is stored in the array. **Type Conversion and Casting** is a way to convert the data type of the array. Here we will use **astype** function to convert the data type of the array. To perform the arithmtric operations we just add them like simple addition.

In [11]:
import numpy as np

# arr_2d = np.array([[1,2,3],[4,5,6]])
# print(arr_2d.shape)
# print(arr_2d.size)
# print(arr_2d.ndim)
# print(arr_2d.dtype)
arr = np.array([1,2,3,4,5,6])

print(arr + 2)
float_arr = arr.astype(float)
print(float_arr)
print(float_arr + 2.5)

[3 4 5 6 7 8]
[1. 2. 3. 4. 5. 6.]
[3.5 4.5 5.5 6.5 7.5 8.5]


## Aggregation Functions
Aggregate functions are used to summarize data. They take a list of values and return a single value. The following aggregation functions are available in Pandas:

| Function | Description |
| --- | --- |
| sum | Sum of values |
| mean | Mean (average) of values |
| median | Median (50th percentile) of values |
| min | Minimum value |
| max | Maximum value |
| std | Standard deviation |
| var | Variance |

Indexing, Fancy Selecting, Boolean Masking, and Sorting

In [ ]:
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
# Indexing
arr[0:2]
# fancy indexing
print(arr[[0,2]])
# Boolean Masking
print(arr[arr > 2])

6
2.0
2.0
1
3
0.816496580927726
[1 3]
[3]


## Reshaping and Manipulating Arrays
Converting or modifying the array without losing the data is known as *reshaping* or *modifying* the array.
For converting the 1d array to a 2d array, we use the `reshape` function. If we want to change the multidimensional array into a 1d array, we use the `flatten` function.
The difference between these two functions ravel and flatten is that ravel returns a view of the array, while flatten returns a copy of the array.

In [22]:
a = np.array([1,2,3,4])
reshaped = a.reshape(2,2)
print(reshaped)
b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b.ravel())
print(b.flatten())

[[1 2]
 [3 4]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Modifications in the Array
There are so many ways to modify the array. Here are some of them. Adding, editing or deleting elements in the array. 
insert function is used to insert elements in the array. Here axis is used to specify the position where the elements are to be inserted. 0 is for rows and 1 for columns. 
append function is used to append elements in the array.
concatenate function is used to concatenate arrays like joining them. 
delete function is used to delete elements in the array.
Stacking arrays is used to stack arrays vertically or horizontally like storing them in a matrix.
Splitting arrays is used to split arrays into smaller arrays.


In [ ]:
import numpy as np
l = np.array([1, 2, 3])
# m = np.insert(l, 2, 5, axis=0)
m = np.copy(l)
new_l = np.append(l, 5)
new_n = np.concatenate((l,m), axis=0)
new_m = np.delete(new_n, 5, axis=0)
# print(np.vstack((l,m)))
# print(np.hstack((l,m)))
# it is simple split there is horizontal split hsplit and vertical split vsplit
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.split(arr, 2))

# print(new_m)

[array([1, 2]), array([3, 4])]


## Boradcasting
We have to implement mathematical operations on arrays. For example, we can add two arrays together, or multiply them. But what if we want to add a number to each element of an array? Or multiply a number to each element of an array? In this case, we need to broadcast the operation. Broadcasting is a way to make the operation work on arrays of different shapes.


In [13]:
import numpy as np
list1 = np.array([1,2,3,4,5,6,7,8,9,10])
discount = 0.1
print(type(list1))

final_price = list1 - (list1*discount)/100

print(final_price)

<class 'numpy.ndarray'>
[0.999 1.998 2.997 3.996 4.995 5.994 6.993 7.992 8.991 9.99 ]


## Missing Values 
In real worl we deal with a lot of missing values and we need to deal with them.
np.nan
np.isnan

To replace the nan values with a specific value, we use the nan_to_num function.
To handle the infinite value we use the isinf function.


In [ ]:
import numpy as np

a = np.array([1, 2, 3, np.nan, 5, np.nan])
cleaned_a = np.nan_to_num(a, nan=4)
print(np.isnan(a))


[False False False  True False  True]
[False False False False False False]
[1. 2. 3. 4. 5. 4.]
